# Site settings
title: PAPER

email: "swear013@gmail.com"
url: "https://norman3.github.io"
github_url: "https://github.com/norman3/papers"
github_editurl: "/blob/master"
github_profile: "https://github.com/norman3"
baseurl: "/papers"
disqus_shortname: norman3github

exclude:
  - README.md
  - _site
  
highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
