# Site settings
title: PAPER

email: "swear013@gmail.com"
upapers: "https://norman3.github.io"
github_upapers: "https://github.com/norman3/papers"
github_editupapers: "/blob/gh-pages"
github_profile: "https://github.com/norman3"
baseupapers: "/papers"
disqus_shortname: norman3github

exclude:
  - README.md
  - _site
  
highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
